var fullName;
console.log("Full Name :", fullName);
fullName = "Pruthviraj Paymal";
console.log(" Full Name :", fullName);
fullName = "Pruthviraj Pandurang Paymal";
console.log(" Full Name  :", fullName);
var myLove = "I LOVE ONLY JS";
console.log(myLove);
var firstName = "Pruthviraj";
var lastName = "Paymal";
var age = "23";
var address = "kolhapur";
var pincode = "416006";
var gender = "Male";
var isMarried = "No";
console.log("First Name :", firstName);
console.log("Last Name :", lastName);
console.log("Age :", age);
console.log("Address :", address);
console.log("Pincode :", pincode);
console.log("Gender :", gender);
console.log("IS Married :", isMarried);
